repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
  - repo: git@github.com:Yelp/detect-secrets
    rev: v0.14.1
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
