variable "zone_id" {}
variable "name" {}
variable "value" {}
variable "proxied" {}
variable "notification_email" {}
variable "domain" {}
variable "pool_name" {}
variable "load_balancer_name" {}
variable "tls" {}
variable "rate_limit" {}
variable "load_balancer_monitor" {}
variable "load_balancer_pool" {}
variable "dns" {}
variable "schemes" {}
variable "methods" {}
variable "statuses" {}
